### ISSUE TITLE
Volunteering

### ISSUE THREAD

**Issue by andrewdea** [ag91/emacs-buddy#12]
I'd like to volunteer as an Emacs buddy. I've been using Emacs since about 2017. I use it mostly to program, both professionally and as a hobby, though I've also used other IDEs like IntelliJ and Eclipse intensively.
I'm not an expert but I'd say I'm decently proficient in Emacs Lisp; over the years I've built a big [init file](https://github.com/andyjda/emacs-configuration/blob/dev/.emacs) from scratch, I've contributed [to a package](https://github.com/emacsorphanage/god-mode), and I've worked on some [additional](https://github.com/andyjda/emacs-configuration/blob/main/.emacs.d/custom/modes/shell-output-mode.el) [features](https://github.com/andyjda/emacs-configuration/blob/main/.emacs.d/custom/packages/all-the-haikus/all-the-haikus.el).

I also speak multiple languages (native English & Italian, proficient Spanish, decent Portuguese and French). My computer-related vocabulary is strictly in English, but I might be able to help Emacs-users who aren't English native-speakers.

Let me know if there's any information you'd need from me! :)

**Comment by ag91** [comment]
hi Andrew, thanks for your kindness! If you could add a row to the table in the README, it would be great. We can do this as you wish: 
1. you create a PR
2. you send me a patch with the table
3. I extract from the issue above some text and make a row (and you tell me if it is fine)
Thanks again!

**Comment by andrewdea** [comment]
Hey, sorry about the late reply! I just saw this.

You can add this row to the table:

 - Andrew 
 - "I'm a software developer using vanilla Emacs since about 2017.
     I use it mostly to program, professionally and as a hobby, and as a note-taking tool."
 - https://github.com/andyjda/

Thanks!

**Comment by ag91** [comment]
thanks!
