### ISSUE TITLE
Some buddies dont have e-mail addresses

### ISSUE THREAD

**Issue by TwiggyWan** [ag91/emacs-buddy#9]
Hi, 

How am I supposed to contact Ranjeeth and Phil who have no email listed anywhere on their links?

It would be beneficial to make sure each buddy has a valid address.

**Comment by ag91** [comment]
it is a good point: I thought people could get in touch with me as I can put you in touch with them :) My concern was about privacy for contacts, but maybe people have other opinions and I could just share them here.

**Comment by TwiggyWan** [comment]
to be honest I failed to see the part about getting in touch with you first.

Therefore my request is not needed : one just needs to read the docs more carefully, kind of like the emacs manual :)
